# Generated by Django 4.1.3 on 2024-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_description_summernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description_summernote',
            field=models.CharField(max_length=50000),
        ),
    ]
