# Generated by Django 4.1.3 on 2024-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_description_summernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.CharField(default='deneme', max_length=50000),
            preserve_default=False,
        ),
    ]
